### ISSUE TITLE
ADMOB cant load advertise

### ISSUE THREAD

**Issue by lekhanhtoan37** [googleads/googleads-mobile-ios-examples#111]
Pls check app id test or ad unit test. It didnt work

**Comment by lveecode** [comment]
Can confirm that this is the case for both real device and the simulator. 

`didFailToReceiveAdWithError` callback is not being helpfull, simply "No ad to show." with no indication that the problem is on AdMob's side

`Error Domain=com.google.admob Code=1 "Request Error: No ad to show." UserInfo={NSLocalizedDescription=Request Error: No ad to show.}`

**Comment by ZaeemZafar** [comment]
@stowy  I am having the same problem mentioned by @Iveecode. 
Just download the GitHub repo and Run the BannerExample.

**Comment by stowy** [comment]
Hi, the test ads account has been temporarily down for the last day or so.
It should be back up within 24 hours.

**Comment by ZaeemZafar** [comment]
Thanks for the update. 

Regards,
Zaeem Zafar

**Comment by padi-dev-toanlk** [comment]
It works again.

Many thanks,

**Comment by lekhanhtoan37** [comment]
It works again.

Many thanks,
