### ISSUE TITLE
DFPBannerView with Native video

### ISSUE THREAD

**Issue by omrih1010** [googleads/googleads-mobile-ios-examples#117]
Trying to work with DFPBannerView with Native video - 
i have 2 small issues : 
1. can i force play the video play in loop?
2. how can i change the play button in the end of the video?
![Screen Shot 2019-08-11 at 17 58 42](https://user-images.githubusercontent.com/4893236/62835473-afdf3000-bc61-11e9-9e8b-74e19eb73e89.png)

**Comment by stowy** [comment]
If you are using native custom templates for your own reservation ads, you
can use custom video controls -
https://developers.google.com/ad-manager/mobile-ads-sdk/ios/custom-video-controls
.

Otherwise for backfill you are limited to only the documented video options
-
https://developers.google.com/ad-manager/mobile-ads-sdk/ios/native/options#gadvideooptions

**Comment by omrih1010** [comment]
Hi , 
I am using **custom_native_style** - any suggestion for this?

**Comment by stowy** [comment]
You can use [custom video controls](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/custom-video-controls) to show your own controls and potentially use the [GADVideoControllerDelegate](https://developers.google.com/admob/ios/api/reference/Classes/GADVideoController#/c:objc(cs)GADVideoController(py)delegate) to get notified when playback ends and then start the video again.

There are no options for changing the not playing UI but test the custom video controls (see [this demo code](https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Objective-C/advanced/APIDemo/APIDemo/GAMCustomVideoControlsController.m) also) to see what you can do.

**Comment by omrih1010** [comment]
thanks!
