### ISSUE TITLE
Use of unersolved identifier 'GADRequest'

### ISSUE THREAD

**Issue by smallhorse87** [googleads/googleads-mobile-ios-examples#19]
After done with 'pod install', I got compile err:  Use of unersolved identifier 'GADRequest'

**Comment by xvilo** [comment]
I am experiencing the same issue...

**Comment by xvilo** [comment]
So I kind of fixed it myself.
1) Copied the pod file from this repository and added my own pods to it.
2) Did a `pod install`
3) Open xCode
4) It worked

Also, when you are getting: "Value of type 'UIView' has no member 'adUnitID' ":
Please be aware that you need to set the class of the bannerview as `GADBannerView ` instead of `UIView`

**Comment by PlayApple** [comment]
me too, unersolved identifier 'GADRequest'

**Comment by ericleich** [comment]
The sample's Podfiles were recently updated to conform to CocoaPods 1.0.0 standards. For those of you seeing the error, have you updated to CocoaPods 1.0.0?

**Comment by PlayApple** [comment]
Cool, I upgraded to 1.0.0 and solved the problem.
