### ISSUE TITLE
@implementation FLTSmartBannerSize - Assigning to 'GADAdSize' from incompatible type

### ISSUE THREAD

**Issue by dakevs** [googleads/googleads-mobile-ios-examples#233]
I am building an app in flutter, and I am using the google_mobile_ads pub. 

My iOS builds are failing now due to this issue:
`Assigning to 'GADAdSize' (aka 'struct GADAdSize') from incompatible type 'GADAdSize (CGFloat)' (aka 'struct GADAdSize (float)')
`
![image](https://user-images.githubusercontent.com/2509364/121666416-14d25f80-ca5e-11eb-9086-15076d439cef.png)

![image](https://user-images.githubusercontent.com/2509364/121666962-ac37b280-ca5e-11eb-9b17-702012b30364.png)

This occurs for both GADPortraitAnchoredAdaptiveBannerAdSizeWithWidth & GADLandScapeAnchoredAdaptiveBannerAdSizeWithWidth

google_mobile_ads: ^0.13.0

Pod Dependencies installed:
Installing Flutter (1.0.0)
Installing Google-Mobile-Ads-SDK (8.5.0)
Installing GoogleAppMeasurement (8.1.0)
Installing GoogleUserMessagingPlatform (2.0.0)
Installing GoogleUtilities (7.4.1)
Installing PromisesObjC (1.2.12)
Installing app_tracking_transparency (0.0.1)
Installing google_mobile_ads (0.0.1)
Installing nanopb (2.30908.0)
Installing url_launcher (0.0.1)

**Comment by ericleich** [comment]
This appears to be because you need to pass a width to the `GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth:` function (see [docs](https://developers.google.com/admob/ios/banner/anchored-adaptive#objective-c) for more info). For example

```
size = GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(320)
```

Note: For Flutter specific questions in the future, please use https://github.com/googleads/googleads-mobile-flutter.
