### ISSUE TITLE
CocoaPods is not the latest version (7.9.1)

### ISSUE THREAD

**Issue by alexliubj** [googleads/googleads-mobile-ios-examples#27]
Still 7.8.1

You are currently using version 7.8.1 of the SDK. Please consider updating your SDK to the most recent SDK version to get the latest features and bug fixes. The latest SDK can be downloaded from http://goo.gl/iGzfsP. A full list of release notes is available at https://developers.google.com/admob/ios/rel-notes.

**Comment by derick182** [comment]
Same problem for me.. no update available when executing pod update.

**Comment by temrich** [comment]
We just added a Podfile.lock to all of our example apps. This will show you the version of the Mobile Ads SDK that we tested the example apps with (currently 7.8.1). However, 7.9.1 is the latest version of our SDK, so if you want to update to that version, simply run "pod update" and it should update all the pods in the Podfile.lock to the latest versions.

Let us know if you have any additional issues updating the Google-Mobile-Ads-SDK pod to 7.9.1.

Thank you!

**Comment by temrich** [comment]
CocoaPods should now be pulling in 7.9.1+ for all example apps.

**Comment by ericleich** [comment]
Google Mobile Ads sometimes does releases outside of the rest of Firebase release schedule. The Firebase pod (which contains Firebase/AdMob subspec) points to the latest Google-Mobile-Ads-SDK pod at the time of that Firebase release. The [latest Firebase release](https://github.com/CocoaPods/Specs/blob/master/Specs/Firebase/3.4.0/Firebase.podspec.json#L49), for example, now points to Google-Mobile-Ads-SDK 7.9.1. However, we have since release Google-Mobile-Ads-SDK 7.10.0.

You can use Google-Mobile-Ads-SDK pod directly instead of Firebase/AdMob if you want to get rid of the "out of date SDK message". But it's perfectly fine to stick with Firebase/AdMob, especially if you're using other Firebase services.

**Comment by moshegottlieb** [comment]
Why is this closed?
I'm using the pod directly (along with other google pods) - `pod 'Google-Mobile-Ads-SDK'` and I'm still seeing this message (for 7.23.0, while 7.26.0 is out there).
Even if I wasn't, and the pod spec would point to an older version with that being the design, making me see this message with absolutely no way to do anything about it is just wrong.

**Comment by stowy** [comment]
@moshegottlieb, are you saying that with the line `pod 'Google-Mobile-Ads-SDK'` in your Podfile, if you run `pod update` that the version of Google Mobile Ads SDK remains at 7.23.0?  This certainly shouldn't be the case. You should get version 7.26.0 if your local podspec repository is updating correctly, you can see the latest podspecs [here](https://github.com/CocoaPods/Specs/tree/master/Specs/5/9/a/Google-Mobile-Ads-SDK/7.26.0).

**Comment by moshegottlieb** [comment]
@stowy - Sorry, did a `pod update --repo-update` and got the latest version.  
My mistake.

**Comment by stowy** [comment]
Great, glad you could resolve.
