### ISSUE TITLE
Getting the error 'GoogleMobileAds/GADInterstitialDelegate.h' file not found

### ISSUE THREAD

**Issue by nihp** [googleads/googleads-mobile-ios-examples#270]
I am trying to migrate the GoogleMobileAds SDK from 7.69.0 to version 9 as per the migration guilde.  I am getting the below errors while trying to migrate.

**I have the imports like the below** 

```
#import <GoogleMobileAds/GADInAppPurchaseDelegate.h>
#import <GoogleMobileAds/GADInterstitialDelegate.h>
```

**Error:**

```
'GoogleMobileAds/GADInterstitialDelegate.h' file not found
'GoogleMobileAds/GADInAppPurchaseDelegate.h' file not found
```

**Comment by ericleich** [comment]
Similar to what I mentioned in https://github.com/googleads/googleads-mobile-ios-examples/issues/18#issuecomment-1127552897, this is expected behavior. The `GADInAppPurchaseDelegate.h` feature is deprecated, and `GADInterstitialDelegate` has been replaced with `GADFullScreenContentDelegate` in iOS version 9.x. See https://developers.google.com/admob/ios/migration#fullscreen for more information, this actually changed in v8.x.
