### ISSUE TITLE
Unable to view correct custom event interstitial google ads IOS

### ISSUE THREAD

**Issue by stefanlam88** [googleads/googleads-mobile-ios-examples#304]
Hi Guys,

Anyone facing same issues whereby i put correct ad unit Id and Zone Id but the google ads I m showing was different from what I set. The ads working fine in android but IOS is different.

Device simulator
16.1.1 IOS

**Comment by JillSong** [comment]
Hi @stefanlam88, we would need more information from you, and steps to reproduce the issue and the SDK version to help investigate. Because we can't take private information through gitHub, please post your question on our support forum for us to take a look https://developers.google.com/admob/ios/support. Thank you!
