### ISSUE TITLE
Clarification: How to support Ogury bidding source as part of AdMob Mediation Adapter?

### ISSUE THREAD

**Issue by jesphinpt** [googleads/googleads-mobile-ios-examples#324]
**Device/Platform Info**
ios

Steps:

1. I am using GoogleMobileAds SDK in my app.
2. Google AdMob mediation is available as part of the mediation adapters.
3. I would like to add Ogury Bidding Source as part of the Bidding Sources list
4. Should I add Ogury Ads SDK to my app or is it not needed to support this integration.

 
I need to know if Admob has the Ogury as one of its mediation networks.
https://developers.google.com/admob/ios/mediate

**Comment by ericleich** [comment]
AdMob does not support Ogury as one of it's official mediation partners.

If you wish to include Ogury in a waterfall mediation context, you can develop a [custom event](https://developers.google.com/admob/ios/custom-events/setup) adapter to do that integration. Some ad networks that are not official partners create and maintain custom events adapters so that individual developers don't have to. I'm not sure whether Ogury has done this or not.

Bidding integrations require a server-side bidder component that would need to be an official integration; that is not supported at this time.
