### ISSUE TITLE
admob iOS flutter : Request Error: No ad to show.

### ISSUE THREAD

**Issue by xds74** [googleads/googleads-mobile-ios-examples#394]
hello, I can't solve this problem on iOS simulator iPhone: message: "Request Error: No ad to show" before it worked and I don't know why it no longer works. I tried on the Android simulator, it works.

**Comment by malandr2** [comment]
Hi @xds74 

It seems your issue is best suited on [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk). This is more of an ad serving issue.

That being said, the googleads-mobile-flutter plugin and ads SDK in general don't have control on ad request fill rate. So I will close this issue as it's not a plugin issue. Thanks!
