### ISSUE TITLE
Rewarded examples not working

### ISSUE THREAD

**Issue by mihailogazda** [googleads/googleads-mobile-ios-examples#43]
Obj-C rewarded example has issue with setup it seems. Console log:

<FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "(null)"
<Google> Invalid Request. Cannot determine request type. Is your ad unit id correct?
Reward based video ad failed to load.

Issue seems with line 31 in AppDelegate.m: 
[GADMobileAds configureWithApplicationID:@"INSERT_APP_ID_HERE"]; 

And on line 103 in ViewController.m
[[GADRewardBasedVideoAd sharedInstance] loadRequest:request                                         withAdUnitID:@"INSERT_AD_UNIT_HERE"];

Same goes for Swift version as well.

**Comment by ericleich** [comment]
The sample apps currently don't run out of the box since you need to insert your own ad unit ID. Now that AdMob recently announced support for its own rewarded ads (previously it only supported mediation), we can update these samples to have working ad units so they run out of the box.

Until this is fixed in the GitHub repo, you can use these IDs (this is what will go into the sample):

App ID: `ca-app-pub-3940256099942544~1458002511`
Ad unit ID: `ca-app-pub-3940256099942544/1712485313`

If you plan to release an app with rewarded ads, you will of course want to go to https://apps.admob.com and create your own rewarded ad unit to use in your app.

**Comment by ericleich** [comment]
Fixed by Pull Request #45
