### ISSUE TITLE
Getting error on setting the rootViewController property of GADInternalBannerView before loading a request.

### ISSUE THREAD

**Issue by syunwei** [googleads/googleads-mobile-ios-examples#472]
Hi 
I got an error when I try to add a Banner View to my app.
The error detail is as follow:
You must set the rootViewController property of <GADInternalBannerView: 0x107c20dd0; frame = (0 0; 393 61); clipsToBounds = YES; hidden = YES; autoresize = W+H; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x600000327040>> before loading a request.

I've added the following code when initial the Banner view which fixed the error.
```
let scenes = UIApplication.shared.connectedScenes
let windowScene = scenes.first as? UIWindowScene
let window = windowScene?.windows.first

banner.rootViewController = window?.rootViewController
```

**Comment by tw-number-one** [comment]
PR: https://github.com/googleads/googleads-mobile-ios-examples/pull/475

**Comment by malandr2** [comment]
Hi @tw-number-one we recommend upgrading to the latest version of the Google Mobile Ads SDK, or at least version 11.0.0 because the [rootViewController](https://developers.google.com/admob/ios/api/reference/Classes/GADBannerView#rootviewcontroller) property is an optional property in SDK version >= 11.0.0

**Comment by syunwei** [comment]
Thank you for pointing out the version @malandr2
Closing the issue now :) 
Thanks!!!
