### ISSUE TITLE
Interstitial positioning problem

### ISSUE THREAD

**Issue by ignitedev** [googleads/googleads-mobile-ios-examples#50]
It is positioned top left, rather than centered vertically and horizontally. Here it is on iPhone 6: 

![image-uploaded-from-ios](https://user-images.githubusercontent.com/5198884/27388397-5d6d1a54-5669-11e7-874b-90bf36de6d3f.png)

**Comment by ericleich** [comment]
The SDK takes the creative returned and throws it in a full screen webview. That particular ad must be limiting its viewport.

If you try out `/6499/example/interstitial` in the DFP interstitial example, that ad consumes the full screen. I believe the main difference is that ad has:

`<meta name="viewport"content="width=device-width,height=device-height,user-scalable=0,minimum-scale=1.0,maximum-scale=1.0"/>`

and I'm guessing this ad limits the viewport to 320x480.

Anyhow, I will close this out since this is not related to the sample app itself. If you require further support on this issue, please relay your question to the [Google Mobile Ads SDK developer forum](groups.google.com/group/google-admob-ads-sdk), which is better suited to answer questions like this.

**Comment by ignitedev** [comment]
thanks for the info!
