### ISSUE TITLE
Rewarded video not showing on device 

### ISSUE THREAD

**Issue by kuldeep13singh** [googleads/googleads-mobile-ios-examples#60]
I have implemented ADMOB Rewarded video in my iOS app.

Rewarded video not showing on the real device..it showing on the test device.. how I can test my video add on the real device.

> Request Error: No ad to show.
I have not implemented meditation on the rewarded video.

How can I get live ads? If I can't get live ads until my app is live then how can I  be convinced that I have implemented ads in the app.

**Comment by ericleich** [comment]
A couple of reasons it might not fill:

1. Ad units take about an hour to warm up. If you recently created an ad unit, it won't start serving right away.
2. Double check your ad unit to make sure it is for the rewarded video ad format, and that it is for the right platform (iOS).

If neither of these are the issue, I recommend you ask this question on the [Google Mobile Ads SDK developer forum](groups.google.com/group/google-admob-ads-sdk) for additional help. I'm closing this issue on the GitHub tracker since it's not an issue with the sample app.
